// <auto-generated />
using System;
using Humans.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable enable

namespace Humans.Infrastructure.Migrations
{
    [DbContext(typeof(HumansDbContext))]
    [Migration("20260210130000_DropLegacyLegalDocumentColumns")]
    partial class DropLegacyLegalDocumentColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally empty — snapshot is maintained in HumansDbContextModelSnapshot.cs
        }
    }
}
