// <auto-generated />
using System;
using Humans.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Humans.Infrastructure.Migrations
{
    [DbContext(typeof(HumansDbContext))]
    [Migration("20260210120000_AddTeamScopedLegalDocuments")]
    partial class AddTeamScopedLegalDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // This migration uses raw SQL for data migration.
            // The target model matches the current HumansDbContextModelSnapshot.
            // Intentionally empty - EF uses the snapshot for the current model state.
#pragma warning restore 612, 618
        }
    }
}
